export const PLANS = {
  labels: {
    features: 'Features',
    сommunity: 'Community',
    enterprise: 'Enterprise',
  },
  cols: [
    {
      rows: '1',
      isRowTitle: true,
      features: 'Ease of use',
      сommunity: '',
      enterprise: '',
    },
    {
      rows: '1',
      isRowTitle: false,
      features: 'Taipy Designer',
      сommunity: false,
      enterprise: true,
    },
    {
      rows: '3',
      isRowTitle: true,
      features: 'Customer Support',
      сommunity: 'Community',
      enterprise: 'dedicated support with SLA',
    },
    {
      rows: '1',
      isRowTitle: true,
      features: 'User management',
      сommunity: '',
      enterprise: '',
    },
    {
      rows: '1',
      isRowTitle: false,
      features: 'Authentication',
      сommunity: false,
      enterprise: true,
    },
    {
      rows: '1',
      isRowTitle: false,
      features: 'Authorization',
      сommunity: false,
      enterprise: true,
    },
    {
      rows: '1',
      isRowTitle: true,
      features: 'Performance & Scalability',
      сommunity: '',
      enterprise: '',
    },
    {
      rows: '2',
      isRowTitle: false,
      features: 'Scenario data management',
      сommunity: 'SQLite, filesystem',
      enterprise: 'MongoDB',
    },
    {
      rows: '2',
      isRowTitle: false,
      features: 'Distributed computing',
      сommunity: false,
      enterprise: true,
    },
    {
      rows: '1',
      isRowTitle: false,
      features: 'Telemetry',
      сommunity: false,
      enterprise: true,
    },
    {
      rows: '1',
      isRowTitle: false,
      features: 'Scheduler',
      сommunity: false,
      enterprise: true,
    },
  ],
};
